CREATE TABLE book (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn13 CHAR(13) NOT NULL,
    title VARCHAR(255) NOT NULL,
    price DECIMAL (13,2) NOT NULL
);

INSERT INTO book (isbn13, title, price) VALUES ('9781430241560', 'Pro Spring MVC: With Web Flow', 39.99);
INSERT INTO book (isbn13, title, price) VALUES ('9781484227909', 'Spring 5 Recipes', 37.44);
INSERT INTO book (isbn13, title, price) VALUES ('9781430259091', 'Spring Recipes', 32.09);
